import './uam_e2e_hp_spec.cy.js'
import './uam_eli_uhp_spec.cy.js'
import './uam_links_spec.cy.js'
import './uam_childs_accomm_spec.cy.js'
import './uam_childs_details_spec.cy.js'
import './uam_labels_spec.cy.js'
import './uam_res_details_spec.cy.js'
import './uam_your_details_spec.cy.js'