import './uam_e2e_hp_spec.cy.js'
import './uam_eli_uhp_spec.cy.js'
import './uam_links_spec.cy.js'
import './uam_val_err_childs_accomm_spec.cy.js'
import './uam_val_err_childs_details_spec.cy.js'
import './uam_val_err_labels_spec.cy.js'
import './uam_val_err_res_details_spec.cy.js'
import './uam_val_err_your_details_spec.cy.js'