const element = require('../../pages/UAM/uam_e2e_hp')
const eligibility = require('../../pages/UAM/eligibility')

describe('[Frontend-UI]: UAM E2E JOURNEY [HAPPY PATH]', function () {
  this.beforeEach(() => {
    cy.newSession()
    cy.fixture('uam_appdata').then(function(uam_secrets){
      this.data = uam_secrets
    })
    cy.visit('/sponsor-a-child/start')
  })

  it('Can submit a complete valid application', function () {
    eligibility.uam_eligibility_steps()
    element.uam_tasklist_page()
    element.your_details_name_step_10()
    element.your_details_othername_step_11()
    element.your_details_othername_step_12()
    element.your_details_othername_step_13()
    element.your_details_contact_details_step_14()
    element.your_details_mobile_step_15()
    element.your_details_additional_details_step_16()
    element.your_details_additional_details_step_18()
    element.your_details_additional_details_step_19()
    element.your_details_additional_details_step_20()
    element.your_details_additional_details_step_21()
    element.your_details_additional_details_step_22()
    element.verify_completed_tasks_1_of_4()
    element.childs_accommodation_step_23()
    element.childs_accommodation_step_24()
    element.childs_accommodation_step_26()
    element.childs_accommodation_step_27()
    element.childs_accommodation_step_28()
    element.verify_completed_tasks_2_of_5()
    element.residents_details_step29()
    element.residents_details_step30()
    element.residents_details_step31()
    element.verify_completed_tasks_3_of_5()
    element.childs_details_step_32()
    element.childs_details_step_33()
    element.childs_details_step_34()
    element.consent_form_step_35()
    element.consent_form_step_36()
    element.ukrconsent_form_step_37()
    element.verify_completed_tasks_4_of_5()
    element.confirmation_page_step_38()
    element.confirmation_page_step_39()
    element.check_answers()
    element.accept_send()
  })
})
