const element = require('../../pages/UAM/uam_your_details')

describe('[Frontend-UI]: UAM YOUR DETAILS [SPONSOR]', function () {
  this.beforeAll(() => {
    cy.newSession()
    cy.fixture('uam_appdata').then(function (uam_secrets) { this.data = uam_secrets })
    cy.fixture('uam_bodytext_err').then(function (uam_bt_err) { this.data = uam_bt_err })
    cy.visit("/sponsor-a-child/start")
  })

  context('[Your Details]', function () {
    it('Validates Your Details correctly', function () {
      element.uam_eligibility_step1_9()
      element.your_details_name_step_10_v1()
      element.your_details_name_step_10_v2()
      element.your_details_name_step_10_v3()
      element.your_details_name_step_10_v4()
      element.your_details_name_step_10_v5()
      element.your_details_name_step_10_v6()
      element.your_details_name_step_10_v7()

      element.your_details_othername_step_12_v8()
      element.your_details_othername_step_12_v9()
      element.your_details_othername_step_12_v10()
      element.your_details_othername_step_12_v11()
      element.your_details_othername_step_12_v12()
      element.your_details_othername_step_12_v13()
      element.your_details_othername_step_12_v14()

      element.your_details_contact_details_step_14_v1()
      element.your_details_contact_details_step_14_v2()
      element.your_details_contact_details_step_14_v3()
      element.your_details_contact_details_step_14_v4()
      element.your_details_contact_details_step_14_v5()
      element.your_details_contact_details_step_14_v6()
      element.your_details_contact_details_step_14_v7()

      element.your_details_mobile_step_15_v1()
      element.your_details_mobile_step_15_v2()
      element.your_details_mobile_step_15_v3()
      element.your_details_mobile_step_15_v4()
      element.your_details_mobile_step_15_v5()
      element.your_details_mobile_step_15_v6()
      element.your_details_mobile_step_15_v7()

      element.your_details_ad_details_id_step_16_v1()
      element.your_details_ad_details_id_step_16_v2()
      element.your_details_ad_details_id_step_16_v3()
      element.your_details_ad_details_id_step_16_v4()
      element.your_details_ad_details_id_step_16_v5()
      element.your_details_ad_details_id_step_16_v6()

      element.your_details_ad_details_dob_step_18_v1()
      element.your_details_ad_details_dob_step_18_v2()
      element.your_details_ad_details_dob_step_18_v3()
      element.your_details_ad_details_dob_step_18_v4()
      element.your_details_ad_details_dob_step_18_v5()
      element.your_details_ad_details_dob_step_18_v6()
      element.your_details_ad_details_dob_step_18_v7()
    })
  })
})
