const element = require('../../pages/UAM/uam_labels')
const elegibility = require('../../pages/UAM/eligibility')

describe('[Frontend-UI]: UAM LABELS', function () {
  this.beforeEach(() => {
    cy.newSession()
    cy.fixture('uam_appdata').then(function(uam_secrets){this.data = uam_secrets})
    cy.fixture('uam_bodytext_err').then(function(uam_bt_err){this.data = uam_bt_err})
    cy.visit("/sponsor-a-child/start")
  })

  it('Has correct error labels for all steps of the application', function () {
    element.uam_eligibility_start()
    element.uam_eligibility_check()
    element.uam_eligibility_step_1()
    element.uam_eligibility_step_2()
    element.uam_eligibility_step_3()
    element.uam_eligibility_step_4()
    element.uam_eligibility_step_5()
    element.uam_eligibility_step_6()
    element.uam_eligibility_step_7()
    element.uam_eligibility_step_9()
    element.uam_eligibility_tasklist()
    
    element.your_details_name_step_10()
    element.your_details_othername_step_11()
    element.your_details_othername_step_12()
    element.your_details_othername_step_13()
    element.your_details_contact_details_step_14()
    element.your_details_mobile_step_15()
    element.your_details_additional_details_step_16()
    element.your_details_prove_id_step_17()
    element.your_details_additional_details_step_18()
    element.your_details_additional_details_step_19()
    element.your_details_additional_details_step_20()
    element.your_details_additional_details_step_21()
    element.your_details_additional_details_step_22()

    element.childs_accommodation_step_23()
    element.childs_accommodation_step_24()
    element.childs_accommodation_step_26()
    element.childs_accommodation_step_27()
    element.childs_accommodation_step_28()

    element.residents_details_step29()
    element.residents_details_step30()
    element.residents_details_step31()

    element.childs_details_step_32()
    element.childs_details_step_33()
    element.childs_details_step_34()
    element.consent_form_step_35()
    element.consent_form_step_36()
    element.ukrconsent_form_step_37()

    element.confirmation_page_step_38()
    element.confirmation_page_step_39()

    element.check_answers()
  })
})
