@startuml Ukraine Sponsor Resettlement Context Diagram
'ref http://plantuml.com/stdlib
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.4.0/C4_Context.puml
!include <office/Users/user.puml>

LAYOUT_TOP_DOWN()
SHOW_PERSON_OUTLINE()
' LAYOUT_AS_SKETCH()

title Ukraine Sponsor Resettlement Context Diagram

Person(applicant, Applicant, "Private & Commercial")
Person_Ext(las, Local Authority)

System_Boundary(system, "Ukraine Sponsor Resettlement") {
  System(resettlement_fe, "Resettlement Web Application", "Front door for applications.")
  System_Ext(share, "Share Service", "Homes for Ukraine application processing service")
  System_Ext(gov_notify, "Gov.UK Notify", "Email & SMS")
}

Rel(applicant, resettlement_fe, "Register expression of interest or sponsor a child")
Rel(resettlement_fe, gov_notify, "User notification")
Rel(resettlement_fe, share, "Transfer on user 'submit'")
Rel(las, share, "View applications")
Rel(gov_notify, applicant, "Confirmation & sms for save and return")

SHOW_DYNAMIC_LEGEND()

center footer  [[https://c4model.com/#CoreDiagrams C4 Context Diagram]]

@enduml