name: Cypress_Run
on:
  workflow_call:

jobs:
  test:
    name: E2E tests
    runs-on: ubuntu-latest
    environment: "production"
    if: github.ref == 'refs/heads/master'
    services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: ukraine
          POSTGRES_DB: ukraine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      INSTANCE_NAME: ukraine-sponsor-resettlement-test
      VCAP_SERVICES: '{"redis":[{"instance_name":"ukraine-sponsor-resettlement-test-redis","credentials":{"uri":"redis://redis"}}],"aws-s3-bucket":[{"instance_name":"ukraine-sponsor-resettlement-test-s3","credentials":{"aws_access_key_id":"access-key-id","aws_secret_access_key":"secret-access-key","aws_region":"eu-west-2","bucket_name":"test-bucket"}}]}'
      GEMFILE_RUBY_VERSION: 3.1.4
      DB_HOST: localhost
      DB_DATABASE: ukraine
      DB_USERNAME: ukraine
      DB_PASSWORD: password
      GOVUK_NOTIFY_API_KEY: ${{ secrets.GOVUK_NOTIFY_API_KEY }}

    steps:
      - name: Setup cypress
        uses: cypress-io/github-action@v4
        with:
          working-directory: automated_tests
          runTests: false

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          working-directory: automated_tests
          start: bundle exec rails server -e test -p 8080
          # quote the url to be safe against YML parsing surprises
          wait-on: "http://localhost:8080"
          browser: chrome
